### ISSUE TITLE
Could you update the build file

### ISSUE THREAD

**Issue by kevinmwangi** [vn38minhtran/react-photoswipe#13]
I am getting this error when i run gulp build:

react-photoswipe.js:1 Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

**Comment by vn38minhtran** [comment]
You can run `npm run build` instead of `gulp build`. https://github.com/vn38minhtran/react-photoswipe/blob/master/package.json#L6
