### ISSUE TITLE
bower file

### ISSUE THREAD

**Issue by flynfish** [vn38minhtran/react-photoswipe#2]
The bower json's main entry is:
`"main": "dist/react-photoswipe.min.js",`

but a dist folder doesn't exit.

**Comment by flynfish** [comment]
Can you add the built version to the repo please?

**Comment by vn38minhtran** [comment]
Please use new version.
https://github.com/vn38minhtran/react-photoswipe#bower
https://github.com/vn38minhtran/react-photoswipe#umd
Example [here](http://codepen.io/vn38minhtran/pen/XmVdvW/)

**Comment by flynfish** [comment]
Thanks so much for the quick response!
