### ISSUE TITLE
Expose handlers for all PhotoSwipe events.

### ISSUE THREAD

**Issue by silentzor** [vn38minhtran/react-photoswipe#5]
It would be great to have access to more handlers that PhotoSwipe exposes (such as "afterChange", "beforeChange", similar to the "close" handler that you are exposing). More info: [PhotoSwipe API](http://photoswipe.com/documentation/api.html)

**Comment by vn38minhtran** [comment]
https://github.com/vn38minhtran/react-photoswipe/releases/tag/v1.0.0
