### ISSUE TITLE
Only a ReactOwner can have refs

### ISSUE THREAD

**Issue by flynfish** [vn38minhtran/react-photoswipe#6]
Have you run into the `Only a ReactOwner can have refs` error when using this lib? I was using it with React .13 and your amd build, but I'm upgrading to .14.5 and now using webpack and I am getting this error.

**Comment by flynfish** [comment]
If I use the dist and include it globally rather than using es6 import statement, it works. Not sure why there would be a difference..

**Comment by vn38minhtran** [comment]
Can you provide to me a example project with this bug ? I will check it for you.

**Comment by flynfish** [comment]
Sorry about this, I finally figured out that it was indeed a 2nd copy of React being included via webpack.
